
POST http://localhost:5000/api/skill
Content-Type: application/json

{
    "name": "CSS"
}
###
GET http://localhost:5000/api/skill
Content-Type: application/json
###
PUT http://localhost:5000/api/skill
Content-Type: application/json

{
    "id": 1,
    "newData": {
        "name": "Swift"
    }
}
###
DELETE http://localhost:5000/api/skill
Content-Type: application/json

{
    "id": 3
}