
POST http://localhost:5000/api/wilder
Content-Type: application/json

{
    "name": "Han Solo",
    "city": "Corellia",
    "skills": "React"
}
###
GET http://localhost:5000/api/wilder
Content-Type: application/json
###
PUT http://localhost:5000/api/wilder
Content-Type: application/json

{
    "id": 1,
    "newData": {
        "name": "John"
    }
}
###
DELETE http://localhost:5000/api/wilder
Content-Type: application/json

{
    "id": 1
}
###
PUT http://localhost:5000/api/addSkill
Content-Type: application/json

{
    "wilderName": "Bobby Doe",
    "skillName": "PHP"
}